# wrangler.toml
name = "barn-labs-landing-page"
main = "src/worker.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "barnlabs-credentials"
database_id = "cc7e9d63-6614-4277-b550-765f6380642f"

[[r2_buckets]]
binding = "ASSETS"
bucket_name = "barnlabs-assets"

[[kv_namespaces]]
binding = "LOGS"
id = "81473c7ba47b4448b5ea6a34513d998d"

# These are non-secret variables
[vars]
SALT_ROUNDS = "10"
MAX_STORAGE_SIZE = "10737418240"
PUBLIC_BUCKET_BASE_URL = "https://bucket1.barnlabs.net"

[observability]
enabled = true